#!/usr/bin/python3
import os
import time
import sys

os.system ("clear")
def slowprint(s):
    for c in s + '\n':
        sys.stdout.write(c)
        sys.stdout.flush()
        time.sleep(5. / 100)

slowprint("Starting the setup...")
os.system ("clear")

slowprint("Welcome to PocketMine-MP Installation (64-bit) - Linux & Windows")
slowprint("Copyright 2022 KeenGames - PocketMine-Setup v1.0.0")
print(" ")
slowprint("-------------------------------------")
print(" ")
slowprint("Created by Keenan Yafiq (keenanyafiqy)")
slowprint("Executed from Python")
slowprint("This installation will install PocketMine-MP v4.x.x")
print(" ")
slowprint("Sometimes packages cannot be downloaded automatically because the packages cannot be located or they're storage is full, so you may needed fast internet connection and many empty storages")
print(" ")
slowprint("-------------------------------------")
print(" ")
choice = input("Do you want to start the installation? [y/n]: ")
if choice == 'n' : sys.exit()
if choice == 'y' : os.system ("clear")

slowprint("You will install:")
slowprint("1. make")
slowprint("2. autoconf")
slowprint("3. automake")
slowprint("4. libtool")
slowprint("5. m4")
slowprint("6. wget")
slowprint("7. getconf")
slowprint("8. gzip")
slowprint("9. bzip2")
slowprint("10. bison")
slowprint("11. g+ or g++")
slowprint("12. cmake")
slowprint("13. pkg-config")
slowprint("14. re2c")
print(" ")

choice = input("Start the setup? (Typing 'n' will cancel the setup!) [y/n]: ")
if choice == 'n' : sys.exit()
if choice == 'y' : os.system ("clear")

slowprint("Starting setup...")
slowprint("Installing 14 packages...")
os.system ("sudo apt install make")
os.system ("sudo apt install autoconf")
os.system ("sudo apt install automake")
os.system ("sudo apt install libtool")
os.system ("sudo apt install m4")
os.system ("sudo apt install wget")
os.system ("sudo apt install getconf")
os.system ("sudo apt install gzip")
os.system ("sudo apt install bzip2")
os.system ("sudo apt install bison")
choice = input("Package g+ or g++ cannot be located, do you want to try it out? [y/n]: ")
if choice == 'n' : slowprint("1 packages installation has been cancelled")
if choice == 'y' : os.system ("sudo apt install g++")
os.system ("sudo apt install cmake")
os.system ("sudo apt install pkg-config")
os.system ("sudo apt install re2c")
os.system ("clear")

choice = input("All/Some required packages are ready. Do you want to install source PocketMine-MP? [y/n]: ")
if choice == 'n' : sys.exit()
if choice == 'y' : os.system ("clear")

slowprint("Installing PocketMine-MP....")
slowprint("Creating folder 'Server'...")
os.system("mkdir Server")
os.system("cd Server")
slowprint("Getting all files from https://get.pmmp.io...")
os.system ("wget -q -O - https://get.pmmp.io | bash -s -")
slowprint("Successfully completed the setup. Type './start.sh' to start the server")
slowprint("This setup cannot start with rooted user and 32-bit OS.")
slowprint("So on Ubuntu in Windows, you might need to exit from root user")
choice = input("Exit? The setup succesfully completed. [y]")
if choice == 'y' : sys.exit()
sys.exit()
